version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: next-template-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://next_user:next_password@mariadb:3306/next_template
    depends_on:
      - mariadb
      - redis
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

  mariadb:
    image: mariadb:10.11
    container_name: next-template-mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=root_password
      - MARIADB_DATABASE=next_template
      - MARIADB_USER=next_user
      - MARIADB_PASSWORD=next_password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./docker/mariadb/init:/docker-entrypoint-initdb.d

  redis:
    image: redis:7-alpine
    container_name: next-template-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  mariadb_data:
  redis_data: